language: cpp

dist: focal  # UBuntu 20.04 LTS https://docs.travis-ci.com/user/reference/focal/

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - g++-10.2
