language: cpp

dist: focal  # UBuntu 20.04 LTS https://docs.travis-ci.com/user/reference/focal/

install:
  - pip install -r requirements.txt

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build .
  - if [ $TRAVIS_BRANCH == "development" || $TRAVIS_BRANCH == "release" ]; then PYTHONPATH="build/test/system" pytest ./test/system; fi